export * from './Categorias'
export * from './Contacto'
export * from './Footer'
export * from './Header/Header'
export * from './Preguntas/Preguntas'
export * from './SearchArea/SearchArea'
export * from './Tiendas'